const kategorieProduktow = [
    {
        id: "all",
        name: "Wszystkie produkty",
        description: "Pełny asortyment tradycyjnego pieczywa, bułek, wyrobów cukierniczych i przekąsek Leks.",
        image: "img/kat_all.png",
        products: []
    },
    {
        id: "chleby",
        name: "Chleby",
        description: "Tradycyjne polskie chleby wypiekane na naturalnym zakwasie.",
        image: "img/kat_chleby.png",
        products: [
            { id: "chleb_helios", name: "Chleb helios", weight: "400g", packaging: "Skrzynka 12 szt. / Paleta: 48 skrzynek (576 szt.)", image: "img/chleb_helios.png", shelfLife: "72h (Świeży)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Pieczywo mieszane pszenno-żytnie z ziarnami." },
            { id: "chleb_zytni_ziarna", name: "Chleb żytni z ziarnami", weight: "400g", packaging: "Skrzynka 12 szt. / Paleta: 48 skrzynek", image: "img/chleb_zytni_ziarna.png", shelfLife: "72h (Świeży)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Chleb żytni z dodatkiem siemienia lnianego i nasion słonecznika, posypany ziarnami prosa i siemieniem lnianym oraz nasionami słonecznika i sezamu." },
            { id: "chleb_pajda", name: "Chleb Pajda", weight: "900g", packaging: "Skrzynka 12 szt.", image: "img/chleb_pajda.jpg", shelfLife: "72h (Świeży)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, isOverviewImage: true, description: "Pieczywo mieszane pszenno – żytnie na naturalnym zakwasie żytnim produkowane metodą wielofazową." },
            { id: "chleb_baltonowski", name: "Chleb Baltonowski", weight: "550g", packaging: "Skrzynka 12 szt. / Paleta: 48 skrzynek (576 szt.)", image: "img/chleb_baltonowski.png", shelfLife: "72h (Świeży)", cert: "IFS Food, BRC Grade A", isFresh: true, isFrozen: false, description: "Pieczywo pszenno-żytnie. Bochenki o kształcie podłużnym, barwa złocisto-brązowa." },
            { id: "chleb_geparda", name: "Chleb Geparda", weight: "450g", packaging: "Skrzynka 15 szt. / Paleta: 48 skrzynek", image: "img/chleb_geparda.png", shelfLife: "72h", cert: "IFS Food", isFresh: true, isFrozen: false, description: "Pieczywo mieszane pszenno-żytnie na zakwasie żytnim z dodatkiem drożdży, z nasionami słonecznika, ziarnem prosa, siemieniem lnianym i nasionami sezamu." },
            { id: "chleb_zloty_klos", name: "Chleb złoty kłos", weight: "400g / 800g", packaging: "Skrzynka 15 szt. / Paleta: 48 skrzynek", image: "img/chleb_zloty_klos.png", shelfLife: "72h", cert: "IFS Food", isFresh: true, isFrozen: false, description: "Pieczywo pszenno-żytnie. Bochenki o kształcie podłużnym, z nacięciami w kształcie X, posypane mąką żytnią typ 720." },
            { id: "chleb_zytni_slonecznik", name: "Chleb żytni ze słonecznikiem", weight: "600g", packaging: "Skrzynka 12 szt. / Paleta: 48 skrzynek (576 szt.)", image: "img/chleb_zytni_slonecznik.png", shelfLife: "72h (Świeży)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Pieczywo żytnie ze słonecznikiem." },
            { id: "chleb_z_maka", name: "Chleb z mąką", weight: "500g", packaging: "Skrzynka 12 szt. / Paleta: 48 skrzynek", image: "img/chleb_z_maka.jpg", shelfLife: "72h (Świeży)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Chleb wyprodukowany jest na kwasie uzyskanym metodą fermentacji wielofazowej z dodatkiem drożdży. Bochenki o kształcie podłużnym, z trzema nacięciami, posypany mąką żytnią typ 720." },
            { id: "chleb_razowy", name: "Chleb razowy", weight: "450g", packaging: "Skrzynka 12 szt. / Paleta: 48 skrzynek", image: "img/chleb_razowy.png", shelfLife: "72h (Świeży)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Pieczywo żytnie razowe pełnoziarniste w formie prostokątnego bochenka." },
            { id: "chleb_wiosenny", name: "Chleb wiosenny z przyprawami i czosnkiem", weight: "400g", packaging: "Karton 12 szt.", image: "img/chleb_wiosenny.jpg", shelfLife: "9 miesięcy (Mrożony)", cert: "IFS Food, BRC", isFresh: false, isFrozen: true, isOverviewImage: true, description: "Pieczywo żytnie z dodatkiem czosnku oraz przypraw (koperek suszony, pietruszka suszona, szczypiorek krojony)." },
            { id: "chleb_wieloziarnisty", name: "Chleb wieloziarnisty", weight: "500g", packaging: "Skrzynka 15 szt. / Paleta: 40 skrzynek (600 szt.)", image: "img/chleb_wieloziarnisty.png", shelfLife: "72h (Świeży)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Pieczywo produkowane z mąki pszennej i żytniej na naturalnym zakwasie z dodatkiem drożdży, soli, ekstraktu słodowego, polepszacza oraz mieszanki ziaren; obsypanego mieszanką ziaren posypką ziarnistą." },
            { id: "chlebek_swieconka", name: "Chlebek do święconki", weight: "60g", packaging: "Karton 30 szt.", image: "img/chlebek_swieconka.jpg", shelfLife: "72h", cert: "IFS Food", isFresh: true, isFrozen: false, isOverviewImage: true, description: "Pieczywo pszenne obsypane mąką żytnią typ 720." },
            { id: "chleb_ig", name: "Chleb IG", weight: "300g", packaging: "Karton 10 szt. / Paleta: 40 kartonów", image: "img/chleb_ig.png", shelfLife: "6 dni", cert: "IFS Food, BRC, Badanie Indeksu Glikemicznego", isFresh: true, isFrozen: false, description: "Pieczywo mieszane o niskim indeksie glikemicznym." },
            { id: "chleb_boryny", name: "Chleb Przysmak Boryny", weight: "400g / 800g", packaging: "Skrzynka 10 szt. / Paleta: 48 skrzynek", image: "img/chleb_boryny.png", shelfLife: "72h", cert: "IFS Food", isFresh: true, isFrozen: false, description: "Pieczywo wyprodukowane na bazie mieszanki do chleba, mąki żytniej, mąki pszennej z dodatkiem kwasu naturalnego, drożdży, soli oraz nasion słonecznika i siemienia lnianego obsypanego mieszanką nasion i płatków ziemniaczanych." },
            { id: "chleb_zytni_bez_drozdzy", name: "Chleb żytni bez drożdży", weight: "500g", packaging: "Karton 10 szt. / Paleta: 48 kartonów", image: "img/chleb_zytni_bez_drozdzy.png", shelfLife: "6 dni", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Chleb żytni wypiekany bez dodatku drożdży." },
            { id: "chleb_zakwas", name: "Chleb na naturalnym zakwasie", weight: "600g", packaging: "Skrzynka 12 szt. / Paleta: 48 skrzynek", image: "img/chleb_zakwas.png", shelfLife: "72h", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Pieczywo mieszane pszenno – żytnie na naturalnym zakwasie żytnim produkowane metodą wielofazową." },
            { id: "chleb_zytni_kapusta", name: "Chleb żytni z kiszoną kapustą", weight: "400g", packaging: "Skrzynka 12 szt.", image: "img/chleb_zytni_kapusta.png", shelfLife: "9 miesięcy (Mrożony)", cert: "IFS Food, BRC", isFresh: false, isFrozen: true, description: "Pieczywo żytnie z dodatkiem kapusty kiszonej." },
            { id: "chleb_zytni_chrzan", name: "Chleb żytni z chrzanem", weight: "400g", packaging: "Skrzynka 12 szt.", image: "img/chleb_zytni_chrzan.png", shelfLife: "9 miesięcy (Mrożony)", cert: "IFS Food, BRC", isFresh: false, isFrozen: true, description: "Pieczywo żytnie z dodatkiem chrzanu tartego i majeranku." },
            { id: "chleb_zytni_papryka", name: "Chleb żytni z papryką", weight: "380g", packaging: "Skrzynka 15 szt.", image: "img/chleb_zytni_papryka.jpg", shelfLife: "9 miesięcy (Mrożony)", cert: "IFS Food, BRC", isFresh: false, isFrozen: true, description: "Pieczywo pszenno-żytnie z pieczoną papryką, posypane mieszanką ziaren sezamu oraz sezamu czarnego." },
            { id: "chleb_baltonowski_z_makiem", name: "Chleb Baltonowski z makiem", weight: "500g", packaging: "Skrzynka 12 szt.", image: "img/chleb_baltonowski_z_makiem.png", shelfLife: "72h (Świeży)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Pieczywo pszenno-żytnie. Bochenki o kształcie podłużnym, barwa złocisto-brązowa. Posypane makiem." }
        ]
    },
    {
        id: "bulki",
        name: "Bułki i rogale",
        description: "Świeże, chrupiące bułki codzienne, grahamki, kajzerki oraz tradycyjne rogale.",
        image: "img/kat_bulki.png",
        products: [
            { id: "bulka_kajzerka", name: "Bułka Kajzerka", weight: "55g", packaging: "Karton 80 szt. / Paleta: 40 kartonów", image: "img/bulka_kajzerka.jpg", shelfLife: "48h (Świeża) / 9 miesięcy (Bake-off)", cert: "IFS Food, BRC Grade A", isFresh: true, isFrozen: false, description: "Pieczywo pszenne wyborowe, charakteryzuje się złocisto-brązową chrupiącą skórką." },
            { id: "bulka_z_ziarnem", name: "Bułka z ziarnem", weight: "70g", packaging: "Karton 60 szt. / Paleta: 40 kartonów", image: "img/bulka_z_ziarnem.jpg", shelfLife: "48h (Świeża) / 9 miesięcy (Bake-off)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Bułka pszenna z ziarnami słonecznika, siemienia lnianego, sezamu, prosa oraz pestkami dyni. Pieczywo przygotowywane z wykorzystaniem odroczonego rozrostu zapewniający dłuższą świeżość produktu." },
            { id: "bulka_wysokobialkowa", name: "Bułka wysokobiałkowa", weight: "80g", packaging: "Karton 50 szt.", image: "img/bulka_wysokobialkowa.png", shelfLife: "9 miesięcy (Mrożona)", cert: "IFS Food, BRC", isFresh: false, isFrozen: true, description: "Pieczywo pszenne na drożdżach z posypką z sezamu i siemienia lnianego. Produkt głęboko mrożony wstępnie zapieczony." },
            { id: "bulka_z_warzywami", name: "Bułka z warzywami", weight: "80g", packaging: "Karton 50 szt. / Paleta: 40 kartonów", image: "img/bulka_z_warzywami.png", shelfLife: "9 miesięcy (Mrożona)", cert: "IFS Food, BRC", isFresh: false, isFrozen: true, description: "Pieczywo pszenne z dodatkiem szpinaku mrożonego, marchwi suszonej, buraka suszonego i cebuli suszonej. Wstępnie podpieczone. Produkt głęboko mrożony" },
            { id: "bulka_grahamka_slonecznik", name: "Bułka grahamka ze słonecznikiem", weight: "75g", packaging: "Karton 60 szt. / Paleta: 40 kartonów", image: "img/bulka_grahamka_slonecznik.jpg", shelfLife: "48h (Świeża) / 9 miesięcy (Bake-off)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Bułka pszenna z mąką pszenną graham z posypką z nasion słonecznika. Pieczywo przygotowywane z wykorzystaniem odroczonego rozrostu zapewniający dłuższą świeżość produktu." },
            { id: "bulka_mleczna", name: "Bułka mleczna", weight: "80g", packaging: "Karton 50 szt. / Paleta: 40 kartonów", image: "img/bulka_mleczna.png", shelfLife: "48h (Świeża)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Pieczywo półcukiernicze pszenne z dodatkiem mleka." },
            { id: "bulka_duza", name: "Bułka duża", weight: "100g", packaging: "Karton 50 szt. / Paleta: 40 kartonów", image: "img/bulka_duza.jpg", shelfLife: "48h (Świeża)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Bułka pszenna, charakteryzuje się złocistą, chrupiącą skórką." },
            { id: "bulka_grahamka", name: "Bułka grahamka", weight: "80g", packaging: "Karton 60 szt. / Paleta: 40 kartonów", image: "img/bulka_grahamka.jpg", shelfLife: "48h (Świeża)", cert: "IFS Food, BRC Grade A", isFresh: true, isFrozen: false, description: "Pieczywo pszenne z dodatkiem mąki graham." },
            { id: "bulka_z_marchewka", name: "Bułka z marchewką", weight: "80g", packaging: "Karton 50 szt.", image: "img/bulka_z_marchewka.png", shelfLife: "9 miesięcy (Mrożona)", cert: "IFS Food, BRC", isFresh: false, isFrozen: true, description: "Pieczywo pszenne z dodatkiem marchwi suszonej, ziarna słonecznika oraz siemienia lnianego. Produkt wstępnie podpieczony, głęboko mrożony." },
            { id: "bulka_poznanska", name: "Bułka poznańska", weight: "80g", packaging: "Karton 60 szt. / Paleta: 40 kartonów", image: "img/bulka_poznanska.jpg", shelfLife: "48h (Świeża)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Bułka pszenna, charakteryzuje się złocistą, chrupiącą skórką." },
            { id: "rogal_z_makiem", name: "Rogal z makiem", weight: "100g", packaging: "Karton 40 szt. / Skrzynka", image: "img/rogal_z_makiem.jpg", shelfLife: "48h (Świeży)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Pieczywo pszenne w kształcie podkowy, posypane makiem." },
            { id: "ciabatta_80g", name: "Ciabatta 80g.", weight: "80g", packaging: "Karton 50 szt. / Paleta: 40 kartonów", image: "img/ciabatta_80g.png", shelfLife: "9 miesięcy (Mrożona)", cert: "IFS Food, BRC", isFresh: false, isFrozen: true, description: "Pieczywo pszenne długo fermentowane wstępnie podpieczone. Produkt głęboko mrożony." },
            { id: "rogal_klasyczny", name: "Rogal", weight: "100g", packaging: "Karton 40 szt. / Skrzynka", image: "img/rogal_klasyczny.jpg", shelfLife: "48h (Świeży) / 9 miesięcy (Mrożony)", cert: "IFS Food, BRC", isFresh: true, isFrozen: true, description: "Pieczywo pszenne o kształcie podkowy z charakterystyczną błyszczącą skórką." },
            { id: "rogal_swiateczny_z_bialym_makiem", name: "Rogal świąteczny z białym makiem", weight: "100g", packaging: "Karton 12 szt.", image: "img/polcukiernicze_rogal_swiateczny_z_bialym_makiem.png", shelfLife: "48h (Świeży)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Pieczywo pszenne półcukiernicze w kształcie półksiężyca, posmarowany pomadą i posypany rozdrobnionymi orzechami arachidowymi. Nadziewany masą makową ze skórką pomarańczową i rodzynkami." },
            { id: "chleb_2ab", name: "Chleb 2AB", weight: "300g", packaging: "Karton 10 szt.", image: "img/chleb_2ab.png", shelfLife: "9 miesięcy (Mrożony)", cert: "IFS Food, BRC, Certyfikat 2AB", isFresh: false, isFrozen: true, description: "Pieczywo pszenne wypiekane z mąki 2AB (mąka pszenna z pradawnych odmian zbóż) na drożdżach." },
            { id: "bulka_2ab", name: "Bułka 2AB", weight: "60g - 70g", packaging: "Karton 60 szt. / Paleta: 40 kartonów", image: "img/bulka_2ab.png", shelfLife: "9 miesięcy (Mrożona)", cert: "IFS Food, BRC, Certyfikat 2AB", isFresh: false, isFrozen: true, description: "Pieczywo pszenne wypiekane z mąki 2AB (mąka pszenna z pradawnych odmian zbóż) na drożdżach" },
            { id: "bagietka_2ab", name: "Bagietka 2AB", weight: "180g - 200g", packaging: "Karton 20 szt.", image: "img/bagietka_2ab.png", shelfLife: "9 miesięcy (Mrożona)", cert: "IFS Food, BRC, Certyfikat 2AB", isFresh: false, isFrozen: true, description: "Pieczywo pszenne wypiekane z mąki 2AB (mąka pszenna z pradawnych odmian zbóż) na drożdżach" }
        ]
    },
    {
        id: "2ab",
        name: "Pieczywo Leks 2AB",
        description: "Pieczywo z pradawnej odmiany pszenicy. Lekkostrawne i bogate w wartości odżywcze.",
        image: "img/kat_2ab.png",
        products: [
            { id: "chleb_2ab", name: "Chleb 2AB", weight: "300g", packaging: "Karton 10 szt.", image: "img/chleb_2ab.png", shelfLife: "9 miesięcy (Mrożony)", cert: "IFS Food, BRC, Certyfikat 2AB", isFresh: false, isFrozen: true, description: "Pieczywo pszenne wypiekane z mąki 2AB (mąka pszenna z pradawnych odmian zbóż) na drożdżach." },
            { id: "bulka_2ab", name: "Bułka 2AB", weight: "60g - 70g", packaging: "Karton 60 szt. / Paleta: 40 kartonów", image: "img/bulka_2ab.png", shelfLife: "9 miesięcy (Mrożona)", cert: "IFS Food, BRC, Certyfikat 2AB", isFresh: false, isFrozen: true, description: "Pieczywo pszenne wypiekane z mąki 2AB (mąka pszenna z pradawnych odmian zbóż) na drożdżach" },
            { id: "bagietka_2ab", name: "Bagietka 2AB", weight: "180g - 200g", packaging: "Karton 20 szt.", image: "img/bagietka_2ab.png", shelfLife: "9 miesięcy (Mrożona)", cert: "IFS Food, BRC, Certyfikat 2AB", isFresh: false, isFrozen: true, description: "Pieczywo pszenne wypiekane z mąki 2AB (mąka pszenna z pradawnych odmian zbóż) na drożdżach" }
        ]
    },
    {
        id: "cukiernia",
        name: "Cukiernia",
        description: "Najwyższej jakości wyroby cukiernicze i ciasta na każdą okazję.",
        image: "img/kat_cukiernia.png",
        products: [
            { id: "skubaniec_z_beza", name: "Ciasto Skubaniec", weight: "kg", packaging: "Karton 1 szt. (Blacha)", image: "img/cukiernia_skubaniec_z_beza.png", shelfLife: "72h (Świeże)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Ciasto z owocami, na półkruchym spodzie." },
            { id: "ciasto_karpatka", name: "Ciasto Karpatka", weight: "kg", packaging: "Karton 1 szt. (Blacha)", image: "img/cukiernia_ciasto_karpatka.png", shelfLife: "48h (Świeże)", cert: "IFS Food", isFresh: true, isFrozen: false, description: "Ciasto parzone przełożone kremem o smaku śmietankowym i udekorowane cukrem dekoracyjnym." },
            { id: "ciasto_krowka", name: "Ciasto Krówka", weight: "kg", packaging: "Karton 1 szt. (Blacha)", image: "img/cukiernia_ciasto_krowka.png", shelfLife: "48h (Świeże)", cert: "IFS Food", isFresh: true, isFrozen: false, description: "Ciasto biszkoptowo-tłuszczowe z kremem o smaku śmietankowym i polewą o smaku toffi, udekorowane płatkami migdałów." },
            { id: "ciasto_z_galaretka", name: "Ciasto z galaretką i truskawkami", weight: "kg", packaging: "Karton 1 szt. (Blacha)", image: "img/cukiernia_ciasto_z_galaretka.png", shelfLife: "48h (Świeże)", cert: "IFS Food", isFresh: true, isFrozen: false, description: "Ciasto biszkoptowo-tłuszczowe z kremem o smaku waniliowo-śmietankowym, truskawkami i galaretką o smaku truskawkowym." },
            { id: "sernik_puszysty", name: "Sernik puszysty", weight: "kg", packaging: "Karton 1 szt. (Blacha)", image: "img/cukiernia_sernik_puszysty.png", shelfLife: "48h (Świeże)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Masa serowa na biszkoptowo-tłuszczowym spodzie udekorowane cukrem dekoracyjnym." },
            { id: "rwaniec_drozdzowy_z_twarogiem", name: "Rwaniec drożdżowy z twarogiem", weight: "450g", packaging: "Karton 1 szt.", image: "img/cukiernia_rwaniec_drozdzowy_z_twarogiem.png", shelfLife: "48h (Świeży)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, isOverviewImage: true, description: "Ciasto drożdżowe z serem twarogowym udekorowane kruszonką i dekoracją cukrową." },
            { id: "baton_coco_crunch", name: "Batony Coco-Crunch", weight: "kg", packaging: "Karton 1 szt. / Tacka", image: "img/cukiernia_baton_coco_crunch.png", shelfLife: "72h (Świeże)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Mix batonów z orzeszkami i nadzieniem o smaku toffi oraz z wiórkami kokosowymi." }
        ]
    },
    {
        id: "polcukiernicze",
        name: "Produkty Półcukiernicze",
        description: "Tradycyjne polskie drożdżówki i słodkie bułki z nadzieniem.",
        image: "img/kat_polcukiernicze.png",
        products: [
            { id: "brioszka_z_lezkami_czekolady", name: "Brioszka z łezkami czekolady", weight: "200g", packaging: "Karton 20 szt. / Skrzynka", image: "img/polcukiernicze_brioszka_z_lezkami_czekolady.png", shelfLife: "48h (Świeża)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Pieczywo półcukiernicze z ciasta drożdżowego z dodatkiem łezek o smaku czekoladowym" },
            { id: "paczek_z_nadzieniem_karpatkowym", name: "Pączek z nadzieniem karpatkowym", weight: "90g", packaging: "Karton 24 szt.", image: "img/polcukiernicze_paczek_z_nadzieniem_karpatkowym.png", shelfLife: "24h (Świeży)", cert: "IFS Food", isFresh: true, isFrozen: false, description: "Pączek z ciasta drożdżowego z nadzieniem budyniowym, polewą cukrową i posypką z białej czekolady" },
            { id: "paczek_z_nadzieniem_malinowym", name: "Pączek z nadzieniem malinowym", weight: "70g - 100g", packaging: "Karton 24 szt.", image: "img/polcukiernicze_paczek_z_nadzieniem_malinowym.png", shelfLife: "24h (Świeży)", cert: "IFS Food", isFresh: true, isFrozen: false, description: "Pączek z ciasta drożdżowego smażonego z nadzieniem o smaku malinowym , dekorowany pomadą wodną i maliną liofizlizowaną" },
            { id: "paczek_z_budyniem", name: "Pączek z budyniem", weight: "70g - 100g", packaging: "Karton 24 szt.", image: "img/polcukiernicze_paczek_z_budyniem.png", shelfLife: "24h (Świeży)", cert: "IFS Food", isFresh: true, isFrozen: false, description: "Pączek z ciasta drożdżowego smażonego z nadzieniem budyniowym , dekorowany pomadą wodną i polewą" },
            { id: "paczek_twarogowy", name: "Pączek twarogowy", weight: "50g", packaging: "Karton 24 szt.", image: "img/polcukiernicze_paczek_twarogowy.png", shelfLife: "24h (Świeży)", cert: "IFS Food", isFresh: true, isFrozen: false, description: "Wyrób cukierniczy z ciasta drożdżowego z dodatkiem sera twarogowego, obtoczony cukrem" },
            { id: "paczek_z_nadzieniem_pistacjowym", name: "Pączek z nadzieniem pistacjowym", weight: "80g", packaging: "Karton 24 szt.", image: "img/polcukiernicze_paczek_z_nadzieniem_pistacjowym.png", shelfLife: "24h (Świeży) / 9 miesięcy (Mrożony)", cert: "IFS Food", isFresh: true, isFrozen: true, description: "Pączek z ciasta drożdżowego smażonego z nadzieniem o smaku pistacjowym , dekorowany pomadą wodną i kostką pistacjową" },
            { id: "paczek_z_marmolada", name: "Pączek z marmoladą", weight: "70g - 100g", packaging: "Karton 24 szt.", image: "img/polcukiernicze_paczek_z_marmolada.png", shelfLife: "24h (Świeży) / 9 miesięcy (Mrożony)", cert: "IFS Food", isFresh: true, isFrozen: true, description: "Pączek z ciasta drożdżowego smażonego z marmoladą o smaku różanym, dekorowany pomadą wodną" },
            { id: "paczek_premium_z_nadzieniem_wisniowym", name: "Pączek premium z nadzieniem wiśniowym", weight: "70g - 100g", packaging: "Karton 24 szt.", image: "img/polcukiernicze_paczek_premium_z_nadzieniem_wisniowym.png", shelfLife: "24h (Świeży) / 9 miesięcy (Mrożony)", cert: "IFS Food, BRC", isFresh: true, isFrozen: true, description: "Pączek z ciasta drożdżowego smażonego z nadzieniem o smaku wiśniowym , dekorowany pomadą wodną i płatkami migdałów" },
            { id: "racuch_z_jablkiem", name: "Racuch z jabłkiem", weight: "90g", packaging: "Karton 20 szt.", image: "img/polcukiernicze_racuch_z_jablkiem.png", shelfLife: "24h (Świeży)", cert: "IFS Food", isFresh: true, isFrozen: false, description: "Pączek z ciasta drożdżowego smażonego z nadzieniem jabłkowym,  dekorowany pomadą" },
            { id: "warkocz_z_lukrem", name: "Warkocz z lukrem", weight: "90g", packaging: "Karton 20 szt. / Skrzynka", image: "img/polcukiernicze_warkocz_z_lukrem.png", shelfLife: "48h (Świeży)", cert: "IFS Food", isFresh: true, isFrozen: false, description: "Wyrób cukierniczy z ciasta drożdżowego, smażony, polany  polewą cukrową." },
            { id: "gniazdko_z_lukrem", name: "Gniazdko", weight: "55g", packaging: "Karton 20 szt.", image: "img/polcukiernicze_gniazdko_z_lukrem.png", shelfLife: "24h (Świeże)", cert: "IFS Food", isFresh: true, isFrozen: false, description: "Wyrób cukierniczy z ciasta parzonego smażonego oblany lukrem" },
            { id: "twist_z_makiem", name: "Twist z makiem", weight: "90g", packaging: "Karton 20 szt. / Skrzynka", image: "img/polcukiernicze_twist_z_makiem.png", shelfLife: "48h (Świeży)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Bułka pszenna drożdżowa z dodatkiem maku" },
            { id: "miniptysie", name: "Miniptysie", weight: "kg", packaging: "Karton zbiorczy", image: "img/cukiernia_miniptysie.png", shelfLife: "24h (Przechowywać w temp. 2-6°C)", cert: "IFS Food", isFresh: true, isFrozen: false, description: "Ciasto parzone z kremem" },
            { id: "calusek", name: "Całusek", weight: "80g", packaging: "Karton 20 szt.", image: "img/polcukiernicze_calusek.png", shelfLife: "48h (Świeży)", cert: "IFS Food", isFresh: true, isFrozen: false, description: "Wyrób cukierniczy z ciasta drożdżowego smażonego, udekorowany cukrem dekoracyjnym" },
            { id: "drozdzowka_z_makiem", name: "Drożdżówka z makiem", weight: "100g", packaging: "Karton 15 szt. / Skrzynka", image: "img/polcukiernicze_drozdzowka_z_makiem.png", shelfLife: "48h (Świeża)", cert: "IFS Food", isFresh: true, isFrozen: false, description: "Pieczywo pszenne półcukiernicze z dodatkiem nadzienia makowego z rodzynkami i dekoracją cukrową" },
            { id: "drozdzowka_z_serem_i_kruszonka", name: "Drożdżówka z serem i kruszonką", weight: "130g", packaging: "Karton 15 szt. / Skrzynka", image: "img/polcukiernicze_drozdzowka_z_serem_i_kruszonka.png", shelfLife: "48h (Świeża) / 9 miesięcy (Mrożona)", cert: "IFS Food, BRC", isFresh: true, isFrozen: true, description: "Pieczywo półcukiernicze pszenne z nadzieniem serowym, posypane kruszonką" }
        ]
    },
    {
        id: "przekaski",
        name: "Słone Przekąski",
        description: "Chrupiące i aromatyczne słone przekąski prosto z pieca.",
        image: "img/kat_przekaski.png",
        products: [
            { id: "paluch_z_serem", name: "Paluch z serem", weight: "80g", packaging: "Karton 40 szt. / Paleta: 48 kartonów", image: "img/paluch_z_serem.png", shelfLife: "48h (Świeży)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Pieczywo pszenne posypane serem gouda" },
            { id: "przekaska_z_serem", name: "Przekąska z serem", weight: "70g", packaging: "Karton 40 szt.", image: "img/przekaska_z_serem.png", shelfLife: "9 miesięcy (Mrożona)", cert: "IFS Food, BRC", isFresh: false, isFrozen: true, description: "Pieczywo pszenne z serem gouda" },
            { id: "wianek_ze_szpinakiem", name: "Wianek ze szpinakiem", weight: "100g", packaging: "Karton 20 szt.", image: "img/wianek_ze_szpinakiem.png", shelfLife: "48h (Świeży)", cert: "IFS Food, BRC", isFresh: true, isFrozen: false, description: "Pieczywo pszenna drożdżowa w kształcie wieńca z dodatkiem sosu beszamel, oraz szpinaku." }
        ]
    }
];
