// Centralna baza danych produktów B2B dla Piekarni Leks Sp. z o.o.
// Podział na 5 głównych kategorii z dokładnymi parametrami logistycznymi.

const PRODUCTS_DATA = {
    // --------------------------------------------------------------------------
    // KATEGORIA 1: Pieczywo Leks 2ab (Ancient Wheat Range)
    // --------------------------------------------------------------------------
    "bulka-2ab": {
        title: "Bułka z pradawnej odmiany pszenicy 2ab",
        category: "2ab",
        categoryLabel: "Pieczywo Leks 2ab",
        image: "img/bulka_2ab.png",
        weight: "80g",
        packaging: "Karton 50 szt. / Paleta: 32 kartony (1600 szt.)",
        ean: "5907552402022",
        temp: "-18°C (Łańcuch głębokiego mrożenia)",
        shelfLife: "12 miesięcy (Bake-off)",
        cert: "IFS Food, BRC, Certyfikat Pszenicy 2AB",
        bake: "Temperatura: 200°C | Czas: 6-7 minut z parowaniem",
        desc: "Wyjątkowa bułka wypiekana z pradawnej odmiany pszenicy 2AB. Charakteryzuje się miękkim, puszystym miękiszem oraz delikatną, chrupiącą skórką. Lekkostrawna formuła i brak sztucznie dodawanego glutenu sprawiają, że produkt cieszy się ogromną popularnością wśród dbających o zdrowie klientów sieci handlowych.",
        ingredients: "Mąka z pradawnej pszenicy 2AB, woda, naturalny kwas pszenny 2AB, drożdże, olej słonecznikowy, sól."
    },
    "chleb-leks-2ab": {
        title: "Chleb z pradawnej odmiany pszenicy 2ab",
        category: "2ab",
        categoryLabel: "Pieczywo Leks 2ab",
        image: "img/chleb_leks_2ab.png",
        weight: "400g (Krojony / Pakowany)",
        packaging: "Karton zbiorczy 10 szt. / Paleta: 40 kartonów (400 szt.)",
        ean: "5907552401025",
        temp: "Temperatura pokojowa (15-22°C)",
        shelfLife: "6 dni (Pakowanie w atmosferze ochronnej MAP)",
        cert: "IFS, BRC, Certyfikat Pradawnej Pszenicy 2AB",
        bake: "Produkt gotowy do spożycia (krojony i pakowany barierowo)",
        desc: "Innowacyjne pieczywo funkcjonalne klasy Premium wyprodukowane z prastarej pszenicy 2AB (pradawna odmiana Triticum turgidum). Chleb charakteryzuje się wyjątkowo wysoką lekkostrawnością, będąc idealną alternatywą dla osób z nadwrażliwością na gluten typu A obecny w pszenicy modyfikowanej przemysłowo.",
        ingredients: "Mąka z pradawnej pszenicy 2AB, naturalny kwas z pszenicy 2AB, woda, ziarna dyni, ziarna słonecznika, sól spożywcza."
    },
    "bagietka-2ab": {
        title: "Bagietka z pradawnej odmiany pszenicy 2ab",
        category: "2ab",
        categoryLabel: "Pieczywo Leks 2ab",
        image: "img/bagietka_2ab.png",
        weight: "250g",
        packaging: "Karton 24 szt. / Paleta: 28 kartonów (672 szt.)",
        ean: "5907552402039",
        temp: "-18°C (Łańcuch mrożony)",
        shelfLife: "9 miesięcy (Bake-off)",
        cert: "IFS Food, BRC, Certyfikat Pszenicy 2AB",
        bake: "Temperatura: 200-210°C | Czas: 8-10 minut (zaparowanie pieca)",
        desc: "Tradycyjna długa bagietka w stylu francuskim, stworzona na bazie innowacyjnej, prastarej pszenicy 2AB. Posiada chrupiącą, poprzecznie naciętą skórkę i duże, nieregularne pory w miękiszu, co jest rzadkością w zautomatyzowanej produkcji przemysłowej.",
        ingredients: "Mąka z pradawnej pszenicy 2AB, woda pitna, drożdże piekarskie, kwas pszenny, sól spożywcza."
    },

    // --------------------------------------------------------------------------
    // KATEGORIA 2: Pieczywo (Chleby i Bułki)
    // --------------------------------------------------------------------------
    // PODKATEGORIA: Chleby
    "chleb-baltonowski": {
        title: "Chleb baltonowski",
        category: "bread_rolls",
        subcategory: "bread",
        categoryLabel: "Chleby",
        image: "img/chleb_baltonowski.png",
        weight: "500g / 600g",
        packaging: "Skrzynka 12 szt. / Paleta: 48 skrzynek (576 szt.)",
        ean: "5907552401049",
        temp: "-18°C (Bake-off) lub Dostawa świeża",
        shelfLife: "72h (Świeży) / 9 miesięcy (Bake-off)",
        cert: "IFS Food, BRC Grade A",
        bake: "Temperatura: 200°C | Czas: 10-12 minut (zaparowanie pieca)",
        desc: "Klasyczny polski chleb mieszany pszenno-żytni, produkowany na naturalnym zakwasie żytnim według tradycyjnej, sprawdzonej receptury. Posiada idealnie puszysty miękisz i chrupiącą, złocistą skórkę.",
        ingredients: "Mąka pszenna typ 750, mąka żytnia typ 720, woda, naturalny kwas żytni, sól spożywcza, drożdże."
    },
    "chleb-helios": {
        title: "Chleb helios",
        category: "bread_rolls",
        subcategory: "bread",
        categoryLabel: "Chleby",
        image: "img/chleb_sielski.png",
        weight: "500g",
        packaging: "Skrzynka 12 szt. / Paleta: 48 skrzynek (576 szt.)",
        ean: "5907552401070",
        temp: "Dostawa świeża lub mrożona",
        shelfLife: "72h (Świeży) / 9 miesięcy (Bake-off)",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 200°C | Czas: 12 minut",
        desc: "Aromatyczny chleb mieszany z delikatną nutą słodu, charakteryzujący się miękkim miękiszem i doskonale przypieczoną skórką. Pieczony na naturalnym zakwasie.",
        ingredients: "Mąka pszenna, mąka żytnia, woda, naturalny zakwas, ekstrakt słodowy jęczmienny, sól, drożdże."
    },
    "chleb-wieloziarnisty": {
        title: "Chleb wieloziarnisty",
        category: "bread_rolls",
        subcategory: "bread",
        categoryLabel: "Chleby",
        image: "img/chleb_sielski.png",
        weight: "400g",
        packaging: "Skrzynka 15 szt. / Paleta: 40 skrzynek (600 szt.)",
        ean: "5907552401056",
        temp: "Dostawa świeża lub mrożona",
        shelfLife: "72h (Świeży) / 9 miesięcy (Bake-off)",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 190°C | Czas: 12-14 minut",
        desc: "Bogaty w ziarna i składniki odżywcze chleb wieloziarnisty, wypiekany z dodatkiem siemienia lnianego, sezamu, płatków owsianych oraz ziaren słonecznika.",
        ingredients: "Mąka pszenna typ 750, woda, ziarna (słonecznik, siemię lniane, sezam), mąka żytnia typ 720, sól, drożdże."
    },
    "chleb-slonecznikowy": {
        title: "Chleb słonecznikowy",
        category: "bread_rolls",
        subcategory: "bread",
        categoryLabel: "Chleby",
        image: "img/chleb_sielski.png",
        weight: "500g",
        packaging: "Skrzynka 12 szt. / Paleta: 48 skrzynek (576 szt.)",
        ean: "5907552401087",
        temp: "Dostawa świeża lub mrożona",
        shelfLife: "72h (Świeży) / 9 miesięcy (Bake-off)",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 200°C | Czas: 11-13 minut",
        desc: "Tradycyjny chleb pszenno-żytni o gęstym miękiszu z dodatkiem dużej ilości łuskanych ziaren słonecznika, które nadają mu przyjemny, orzechowy aromat.",
        ingredients: "Mąka pszenna, mąka żytnia, woda, łuskane ziarna słonecznika, kwas żytni, sól, drożdże."
    },
    "chleb-zytni-bez-drozdzy": {
        title: "Chleb żytni bez drożdży",
        category: "bread_rolls",
        subcategory: "bread",
        categoryLabel: "Chleby",
        image: "img/chleb_sulecinski.png",
        weight: "500g (Krojony / Pakowany)",
        packaging: "Karton 10 szt. / Paleta: 48 kartonów",
        ean: "5907552401094",
        temp: "Temperatura pokojowa ( MAP Flow-pack)",
        shelfLife: "6 dni",
        cert: "IFS Food, BRC",
        bake: "Produkt gotowy do spożycia",
        desc: "W 100% naturalny chleb żytni, fermentowany wyłącznie na gęstym, wielofazowym zakwasie żytnim, całkowicie bez dodatku drożdży piekarskich. Dedykowany dla alergików.",
        ingredients: "Mąka żytnia typ 720, naturalny zakwas żytni, woda pitna, sól spożywcza."
    },
    "chleb-zakwas": {
        title: "Chleb na naturalnym zakwasie",
        category: "bread_rolls",
        subcategory: "bread",
        categoryLabel: "Chleby",
        image: "img/chleb_sielski.png",
        weight: "500g",
        packaging: "Skrzynka 12 szt. / Paleta: 48 skrzynek",
        ean: "5907552401100",
        temp: "Dostawa świeża",
        shelfLife: "72h",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 200°C | Czas: 10 minut (dla mrożonego)",
        desc: "Klasyczny, rzemieślniczy chleb mieszany, pieczony metodą tradycyjną na bazie naturalnego kwasu chlebowego. Posiada popękaną, chrupiącą skórkę.",
        ingredients: "Mąka żytnia typ 720, mąka pszenna typ 750, woda, naturalny kwas żytni, sól spożywcza."
    },
    "chleb-boryna": {
        title: "Chleb Przysmak Boryny",
        category: "bread_rolls",
        subcategory: "bread",
        categoryLabel: "Chleby",
        image: "img/chleb_sielski.png",
        weight: "600g",
        packaging: "Skrzynka 10 szt. / Paleta: 48 skrzynek",
        ean: "5907552401117",
        temp: "Dostawa świeża",
        shelfLife: "72h",
        cert: "IFS Food",
        bake: "Produkt gotowy do spożycia",
        desc: "Wiejski, duży bochenek o wyrazistym, głębokim smaku z dodatkiem naturalnego słodu ciemnego i ziemniaków, co zapewnia niezwykłą wilgotność i świeżość.",
        ingredients: "Mąka pszenna, mąka żytnia, woda, naturalny kwas, płatki ziemniaczane, ciemny słód jęczmienny, sól."
    },
    "chleb-domowy": {
        title: "Chleb domowy",
        category: "bread_rolls",
        subcategory: "bread",
        categoryLabel: "Chleby",
        image: "img/chleb_sielski.png",
        weight: "500g",
        packaging: "Skrzynka 12 szt. / Paleta: 48 skrzynek",
        ean: "5907552401124",
        temp: "Dostawa świeża",
        shelfLife: "72h",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 200°C | Czas: 12 minut",
        desc: "Rustykalny, podłużny bochenek o delikatnym miękiszu. Idealnie oddaje smak chleba pieczonego w domowym piecu, opartego na tradycyjnym kwasie.",
        ingredients: "Mąka pszenna typ 750, mąka żytnia typ 720, woda, kwas naturalny, sól, drożdże."
    },
    "chleb-razowy": {
        title: "Chleb razowy",
        category: "bread_rolls",
        subcategory: "bread",
        categoryLabel: "Chleby",
        image: "img/chleb_sulecinski.png",
        weight: "500g",
        packaging: "Skrzynka 12 szt. / Paleta: 48 skrzynek",
        ean: "5907552401131",
        temp: "Dostawa świeża lub mrożona",
        shelfLife: "72h (Świeży) / 9 miesięcy (Mrożony)",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 200°C | Czas: 14 minut",
        desc: "Ciemny, tradycyjny chleb razowy o wysokiej zawartości błonnika, wypiekany z mąki żytniej razowej z pełnego przemiału ziarna. Doskonały dla diabetyków.",
        ingredients: "Mąka żytnia razowa typ 2000, woda, naturalny kwas żytni, sól spożywcza."
    },
    "chleb-klos": {
        title: "Chleb złoty kłos",
        category: "bread_rolls",
        subcategory: "bread",
        categoryLabel: "Chleby",
        image: "img/chleb_sielski.png",
        weight: "400g",
        packaging: "Skrzynka 15 szt. / Paleta: 48 skrzynek",
        ean: "5907552401148",
        temp: "Dostawa świeża",
        shelfLife: "72h",
        cert: "IFS Food",
        bake: "Produkt gotowy do spożycia",
        desc: "Wyjątkowy chleb mieszany z dodatkiem ziaren soi, siemienia lnianego i słonecznika, o pięknej, złocistej skórce z nacięciem w kształcie kłosu.",
        ingredients: "Mąka pszenna, woda, mąka żytnia, ziarna (soja, słonecznik, siemię lniane), kwas naturalny, sól."
    },
    "chleb-ig": {
        title: "Chleb IG (o niskim indeksie glikemicznym)",
        category: "bread_rolls",
        subcategory: "bread",
        categoryLabel: "Chleby",
        image: "img/chleb_leks_2ab.png",
        weight: "400g (Krojony / Pakowany)",
        packaging: "Karton 10 szt. / Paleta: 40 kartonów",
        ean: "5907552401155",
        temp: "Temperatura pokojowa (MAP Flow-pack)",
        shelfLife: "6 dni",
        cert: "IFS Food, BRC, Badanie Indeksu Glikemicznego",
        bake: "Produkt gotowy do bezpośredniego spożycia",
        desc: "Pieczywo funkcjonalne o potwierdzonym klinicznie niskim indeksie glikemicznym (IG < 55). Bogate w białko i błonnik, idealne dla diabetyków i osób na diecie redukcyjnej.",
        ingredients: "Woda, mąka żytnia, mąka pszenna, białko pszenne, siemię lniane, błonnik owsiany, sezam, drożdże, sól."
    },
    "chleb-sielski": {
        title: "Chleb sielski",
        category: "bread_rolls",
        subcategory: "bread",
        categoryLabel: "Chleby",
        image: "img/chleb_sielski.png",
        weight: "500g",
        packaging: "Skrzynka 12 szt. / Paleta: 48 skrzynek (576 szt.)",
        ean: "5907552401032",
        temp: "-18°C (Bake-off) lub Dostawa świeża",
        shelfLife: "72h (Świeży) / 9 miesięcy (Bake-off)",
        cert: "IFS Food, BRC Grade A",
        bake: "Temperatura: 200°C | Czas: 12-14 minut z zaparowaniem",
        desc: "Okrągły, rustykalny bochenek chleba o silnym, tradycyjnym charakterze. Chleb Sielski pieczony jest z mieszanki mąk żytnich i pszennych na gęstym naturalnym zakwasie Sulęcińskim.",
        ingredients: "Mąka pszenna typ 750, mąka żytnia typ 720, woda, naturalny kwas żytni, sól, drożdże piekarskie."
    },
    "chleb-gepard": {
        title: "Chleb Geparda",
        category: "bread_rolls",
        subcategory: "bread",
        categoryLabel: "Chleby",
        image: "img/chleb_sielski.png",
        weight: "400g",
        packaging: "Skrzynka 15 szt. / Paleta: 48 skrzynek",
        ean: "5907552401162",
        temp: "Dostawa świeża",
        shelfLife: "72h",
        cert: "IFS Food",
        bake: "Produkt gotowy do spożycia",
        desc: "Innowacyjny chleb pszenno-żytni o unikalnym wzorze cętkowanej skórki, uzyskiwanym dzięki specjalnej, naturalnej paście ryżowej nakładanej przed wypiekiem.",
        ingredients: "Mąka pszenna, mąka żytnia, woda, pasta ryżowa (posypka), kwas naturalny, sól, drożdże."
    },
    "chleb-zytni-ziarna": {
        title: "Chleb żytni z ziarnami",
        category: "bread_rolls",
        subcategory: "bread",
        categoryLabel: "Chleby",
        image: "img/chleb_sulecinski.png",
        weight: "500g",
        packaging: "Skrzynka 12 szt. / Paleta: 48 skrzynek",
        ean: "5907552401179",
        temp: "Dostawa świeża lub mrożona",
        shelfLife: "72h (Świeży) / 9 miesięcy (Mrożony)",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 200°C | Czas: 12-14 minut",
        desc: "Zdrowy chleb żytni wypiekany na zakwasie żytnim, obficie wypełniony ziarnami siemienia lnianego, słonecznika oraz płatkami żytnimi.",
        ingredients: "Mąka żytnia typ 720, woda, ziarna (słonecznik, siemię lniane), kwas naturalny, sól."
    },
    "chleb-zytni-slonecznik": {
        title: "Chleb żytni ze słonecznikiem",
        category: "bread_rolls",
        subcategory: "bread",
        categoryLabel: "Chleby",
        image: "img/chleb_sulecinski.png",
        weight: "500g",
        packaging: "Skrzynka 12 szt. / Paleta: 48 skrzynek (576 szt.)",
        ean: "5907552401063",
        temp: "Dostawa świeża lub mrożona",
        shelfLife: "72h (Świeży) / 9 miesięcy (Bake-off)",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 200°C | Czas: 12-15 minut z zaparowaniem",
        desc: "Ciemny chleb w 100% żytni, wypiekany na naturalnym zakwasie żytnim z obfitym dodatkiem łuskanych ziaren słonecznika. Charakteryzuje się gęstym, wilgotnym miękiszem.",
        ingredients: "Mąka żytnia typ 720, naturalny zakwas żytni, woda, ziarna słonecznika, sól spożywcza."
    },

    // PODKATEGORIA: Bułki i Rogale
    "bulka-duza": {
        title: "Bułka duża",
        category: "bread_rolls",
        subcategory: "rolls",
        categoryLabel: "Bułki i Rogale",
        image: "img/bulka_grahamka.png",
        weight: "90g",
        packaging: "Karton 60 szt. / Paleta: 32 kartony",
        ean: "5907552402060",
        temp: "-18°C (Bake-off)",
        shelfLife: "9 miesięcy",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 200°C | Czas: 6 minut bez rozmrażania",
        desc: "Klasyczna, duża bułka pszenna śniadaniowa o puszystym miękiszu i delikatnej chrupiącej skórce. Znakomita baza pod kanapki B2B.",
        ingredients: "Mąka pszenna typ 500, woda, drożdże, tłuszcz roślinny, sól."
    },
    "bulka-kajzerka": {
        title: "Bułka kajzerka",
        category: "bread_rolls",
        subcategory: "rolls",
        categoryLabel: "Bułki i Rogale",
        image: "img/bulka_kajzerka.png",
        weight: "50g",
        packaging: "Karton 100 szt. / Paleta: 32 kartony (3200 szt.)",
        ean: "5907552402046",
        temp: "-18°C (głębokie mrożenie)",
        shelfLife: "12 miesięcy (Bake-off)",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 210°C | Czas: 5-6 minut bez rozmrażania",
        desc: "Najpopularniejsza bułka w Polsce, wypiekana z najwyższej jakości mąki pszennej. Charakteryzuje się chrupiącą złocistą skórką i tradycyjnym, pięcioramiennym nacięciem.",
        ingredients: "Mąka pszenna typ 500, woda, drożdże piekarskie, tłuszcze roślinne, sól, polepszacz piekarniczy."
    },
    "bulka-grahamka": {
        title: "Bułka grahamka",
        category: "bread_rolls",
        subcategory: "rolls",
        categoryLabel: "Bułki i Rogale",
        image: "img/bulka_grahamka.png",
        weight: "70g",
        packaging: "Karton 60 szt. / Paleta: 32 kartony (1920 szt.)",
        ean: "5907552402015",
        temp: "-18°C (Łańcuch głębokiego mrożenia)",
        shelfLife: "12 miesięcy (Bake-off)",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 210°C | Czas: 6-8 minut (wypiek bez rozmrażania)",
        desc: "Chrupiąca, pożywna bułka grahamka wypiekana z mąki z pełnego przemiału pszenicy graham. Posiada wysoką zawartość błonnika pokarmowego oraz cenne minerały.",
        ingredients: "Mąka pszenna graham typ 1850, mąka pszenna typ 750, woda pitna, drożdże, sól spożywcza, olej roślinny."
    },
    "bulka-grahamka-slonecznik": {
        title: "Bułka grahamka z ziarnem słonecznika",
        category: "bread_rolls",
        subcategory: "rolls",
        categoryLabel: "Bułki i Rogale",
        image: "img/bulka_grahamka.png",
        weight: "75g",
        packaging: "Karton 60 szt. / Paleta: 32 kartony",
        ean: "5907552402077",
        temp: "-18°C",
        shelfLife: "12 miesięcy",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 200°C | Czas: 7 minut",
        desc: "Doskonała, pożywna bułka grahamka, wypiekana z dodatkiem łuskanych ziaren słonecznika, które wzbogacają ją o chrupkość i cenne kwasy tłuszczowe.",
        ingredients: "Mąka graham, mąka pszenna, woda, ziarna słonecznika, olej, drożdże, sól."
    },
    "rogal-mak": {
        title: "Rogal z makiem",
        category: "bread_rolls",
        subcategory: "rolls",
        categoryLabel: "Bułki i Rogale",
        image: "img/bulka_kajzerka.png",
        weight: "80g",
        packaging: "Karton 50 szt. / Skrzynka 15 szt.",
        ean: "5907552402084",
        temp: "Dostawa świeża lub mrożona",
        shelfLife: "48h (Świeży) / 9 miesięcy (Mrożony)",
        cert: "IFS Food",
        bake: "Temperatura: 195°C | Czas: 6 minut",
        desc: "Klasyczny, puszysty rogal pszenny o delikatnie maślanym smaku, obficie posypany niebieskim makiem. Prawdziwy smak tradycyjnego polskiego śniadania.",
        ingredients: "Mąka pszenna typ 500, woda, masło, cukier, drożdże, sól, niebieski mak."
    },
    "bulka-activ": {
        title: "Bułka activ",
        category: "bread_rolls",
        subcategory: "rolls",
        categoryLabel: "Bułki i Rogale",
        image: "img/bulka_grahamka.png",
        weight: "80g",
        packaging: "Karton 60 szt. / Paleta: 32 kartony",
        ean: "5907552402091",
        temp: "-18°C (Bake-off)",
        shelfLife: "9 miesięcy",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 200°C | Czas: 6-7 minut",
        desc: "Pieczywo funkcjonalne z dodatkiem błonnika, siemienia lnianego, soi i kiełków pszenicy. Dedykowane dla aktywnych konsumentów dbających o zdrową dietę.",
        ingredients: "Mąka pszenna, woda, soja, siemię lniane, otręby pszenne, kiełki pszenicy, sól, drożdże."
    },
    "bulka-mleczna": {
        title: "Bułka mleczna",
        category: "bread_rolls",
        subcategory: "rolls",
        categoryLabel: "Bułki i Rogale",
        image: "img/bulka_kajzerka.png",
        weight: "50g",
        packaging: "Karton 80 szt. / Skrzynka 20 szt.",
        ean: "5907552402107",
        temp: "Dostawa świeża",
        shelfLife: "48h",
        cert: "IFS Food",
        bake: "Produkt gotowy do spożycia",
        desc: "Delikatna, puszysta bułeczka o słodkawym smaku, wypiekana z dodatkiem naturalnego mleka i masła. Niezwykle miękka i uwielbiana przez dzieci.",
        ingredients: "Mąka pszenna typ 500, mleko pasteryzowane, woda, cukier, masło, drożdże, sól."
    },
    "bulka-poznanska": {
        title: "Bułka poznańska",
        category: "bread_rolls",
        subcategory: "rolls",
        categoryLabel: "Bułki i Rogale",
        image: "img/bulka_kajzerka.png",
        weight: "70g",
        packaging: "Karton 60 szt. / Skrzynka 15 szt.",
        ean: "5907552402114",
        temp: "Dostawa świeża lub mrożona",
        shelfLife: "48h (Świeży) / 9 miesięcy (Mrożony)",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 210°C | Czas: 5 minut",
        desc: "Tradycyjna, podłużna bułka pszenna z charakterystycznym przedziałkiem na wierzchu, o chrupiącej skórce i sprężystym, delikatnym miękiszu.",
        ingredients: "Mąka pszenna typ 500, woda, drożdże piekarskie, tłuszcz, sól."
    },
    "bulka-dynia": {
        title: "Bułka z dynią",
        category: "bread_rolls",
        subcategory: "rolls",
        categoryLabel: "Bułki i Rogale",
        image: "img/bulka_grahamka.png",
        weight: "75g",
        packaging: "Karton 60 szt. / Paleta: 32 kartony (1920 szt.)",
        ean: "5907552402053",
        temp: "-18°C (Bake-off)",
        shelfLife: "12 miesięcy (Bake-off)",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 200°C | Czas: 6-7 minut z parowaniem",
        desc: "Wyjątkowa bułka pszenno-żytnia o chrupiącej skórce, obficie posypana pestkami dyni, które podczas wypieku uwalniają niesamowity, orzechowy aromat.",
        ingredients: "Mąka pszenna typ 750, woda, pestki dyni, mąka żytnia typ 720, płatki owsiane, drożdże, sól."
    },
    "bulka-ziarno": {
        title: "Bułka z ziarnem",
        category: "bread_rolls",
        subcategory: "rolls",
        categoryLabel: "Bułki i Rogale",
        image: "img/bulka_grahamka.png",
        weight: "80g",
        packaging: "Karton 60 szt. / Paleta: 32 kartony",
        ean: "5907552402121",
        temp: "-18°C (Bake-off)",
        shelfLife: "12 miesięcy",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 200°C | Czas: 7 minut",
        desc: "Wieloziarnista bułka śniadaniowa o wspaniałej ciemnej barwie, obficie posypana ziarnami słonecznika, siemienia lnianego i sezamu.",
        ingredients: "Mąka pszenna, mąka żytnia, woda, siemię lniane, słonecznik, sezam, słód jęczmienny, sól, drożdże."
    },

    // --------------------------------------------------------------------------
    // KATEGORIA 3: Cukiernia (Ciasta i Torty)
    // --------------------------------------------------------------------------
    "ciasto-galaretka": {
        title: "Ciasto z galaretką i truskawkami",
        category: "cakes",
        categoryLabel: "Cukiernia",
        image: "img/kategoria_cukiernia.png",
        weight: "1.4kg",
        packaging: "Karton 2 blachy / Paleta: 36 kartonów",
        ean: "5907552404033",
        temp: "-18°C (głęboko mrożone)",
        shelfLife: "6 miesięcy",
        cert: "IFS Food",
        bake: "Rozmrażać przez 3 godziny w warunkach chłodniczych",
        desc: "Lekkie, orzeźwiające ciasto biszkoptowe z grubą warstwą puszystego kremu śmietankowego, udekorowane świeżymi truskawkami zatopionymi w krystalicznej, czerwonej galaretce truskawkowej.",
        ingredients: "Galaretka truskawkowa, truskawki świeże 20%, śmietana 30%, biszkopt (jaja, mąka pszenna, cukier), aromat."
    },
    "ciasto-krowka": {
        title: "Ciasto krówka",
        category: "cakes",
        categoryLabel: "Cukiernia",
        image: "img/kategoria_cukiernia.png",
        weight: "1.3kg",
        packaging: "Karton 2 blachy",
        ean: "5907552404040",
        temp: "-18°C",
        shelfLife: "6 miesięcy",
        cert: "IFS Food",
        bake: "Rozmrażać przez 4 godziny w temp. 2-6°C",
        desc: "Wyśmienite ciasto deserowe z warstwą delikatnego kremu śmietankowego oraz gęstej, aksamitnej masy kajmakowej (krówkowej), przełożone chrupiącymi krakersami i posypane płatkami migdałowymi.",
        ingredients: "Masa krówkowa (kajmak), krakersy, śmietanka, masło 82%, płatki migdałowe, wanilia."
    },
    "sernik-puszysty": {
        title: "Sernik puszysty",
        category: "cakes",
        categoryLabel: "Cukiernia",
        image: "img/kategoria_cukiernia.png",
        weight: "1.5kg (Blacha zbiorcza)",
        packaging: "Karton 4 szt. / Paleta: 24 kartony (96 szt.)",
        ean: "5907552404019",
        temp: "-18°C (głęboko mrożone)",
        shelfLife: "6 miesięcy (Łańcuch mrożony)",
        cert: "IFS Food",
        bake: "Rozmrażać przez 4 godziny w temperaturze chłodniczej (2-6°C)",
        desc: "Klasyczny, puszysty i wilgotny sernik premium przygotowywany z trzykrotnie mielonego, naturalnego twarogu tłustego o wyjątkowo gładkiej strukturze. Wypiekany bez dodatku mąki, na chrupiącym kruchym spodzie maślanym.",
        ingredients: "Twaróg tłusty naturalny 70%, masa jajowa, cukier, masło 82%, mąka pszenna (spód), naturalny aromat waniliowy."
    },
    "ciasto-skubaniec": {
        title: "Ciasto skubaniec z bezą",
        category: "cakes",
        categoryLabel: "Cukiernia",
        image: "img/kategoria_cukiernia.png",
        weight: "1.2kg",
        packaging: "Karton 2 blachy",
        ean: "5907552404057",
        temp: "-18°C",
        shelfLife: "6 miesięcy",
        cert: "IFS Food",
        bake: "Rozmrażać 3 godziny w temperaturze pokojowej",
        desc: "Tradycyjne ciasto pleśniak (skubaniec) składające się z warstw skubanego ciasta kruchego (jasnego i kakaowego), kwaskowatego nadzienia porzeczkowego oraz grubej, puszystej, zapieczonej bezy.",
        ingredients: "Mąka pszenna, jaja, cukier, kakao, konfitura z czarnej porzeczki, masło, beza."
    },
    "ciasto-karpatka": {
        title: "Ciasto karpatka",
        category: "cakes",
        categoryLabel: "Cukiernia",
        image: "img/kategoria_cukiernia.png",
        weight: "1.2kg (Blacha)",
        packaging: "Karton 4 szt. / Paleta: 24 kartony (96 szt.)",
        ean: "5907552404026",
        temp: "-18°C (głęboko mrożone)",
        shelfLife: "6 miesięcy (Łańcuch mrożony)",
        cert: "IFS Food, BRC",
        bake: "Rozmrażać przez 3-4 godziny w temperaturze chłodniczej (2-6°C)",
        desc: "Kultowe polskie ciasto z puszystym kremem budyniowo-maślanym, ułożonym między dwoma warstwami karbowanego ciasta ptysiowego przypominającego góry Karpaty.",
        ingredients: "Krem budyniowo-maślany (mleko, masło 82%, cukier, żółtka), mąka pszenna, woda, jaja kurze, cukier puder."
    },
    "placek-twarog": {
        title: "Placek z twarogiem",
        category: "cakes",
        categoryLabel: "Cukiernia",
        image: "img/kategoria_cukiernia.png",
        weight: "1.3kg",
        packaging: "Karton 2 blachy",
        ean: "5907552404064",
        temp: "Dostawa świeża lub mrożona",
        shelfLife: "72h (Świeży) / 6 miesięcy (Mrożony)",
        cert: "IFS Food",
        bake: "Rozmrażać przez 3 godziny w temp. pokojowej",
        desc: "Domowy placek drożdżowy z obfitą, grubą warstwą słodkiego, naturalnego twarogu i delikatną kruszonką maślaną. Doskonały, tradycyjny wypiek na co dzień.",
        ingredients: "Mąka pszenna typ 500, twaróg naturalny, woda, cukier, masło, jaja, drożdże, kruszonka."
    },
    "miniptysie": {
        title: "Miniptysie",
        category: "cakes",
        categoryLabel: "Cukiernia",
        image: "img/kategoria_cukiernia.png",
        weight: "500g (Opakowanie zbiorcze)",
        packaging: "Karton 8 opakowań",
        ean: "5907552404071",
        temp: "-18°C",
        shelfLife: "6 miesięcy",
        cert: "IFS Food",
        bake: "Rozmrażać przez 1.5 godziny w temperaturze chłodniczej",
        desc: "Malutkie, puszyste ptysie z ciasta parzonego w 100% wypełnione lekką, bitą śmietaną, oprószone cukrem pudrem. Idealna i szybka propozycja deserowa B2B.",
        ingredients: "Śmietana 30% (bita), ciasto ptysiowe (mąka pszenna, jaja, woda, tłuszcz), cukier puder."
    },
    "tort-dark": {
        title: "Tort dark",
        category: "cakes",
        categoryLabel: "Cukiernia",
        image: "img/kategoria_cukiernia.png",
        weight: "1.2kg (Średnica 22cm)",
        packaging: "Karton 1 szt. / Paleta: 48 kartonów",
        ean: "5907552404088",
        temp: "-18°C (głęboko mrożone)",
        shelfLife: "6 miesięcy",
        cert: "IFS Food, BRC",
        bake: "Rozmrażać przez 4 godziny w warunkach chłodniczych",
        desc: "Luksusowy tort czekoladowy dedykowany dla prawdziwych koneserów. Ciemne, mocno kakaowe biszkopty przełożone aksamitnym musem z gorzkiej belgijskiej czekolady.",
        ingredients: "Gorzka czekolada belgijska 60%, śmietanka, cukier, jaja, mąka pszenna, likier waniliowy (aromat)."
    },
    "tort-karmel": {
        title: "Tort karmel",
        category: "cakes",
        categoryLabel: "Cukiernia",
        image: "img/kategoria_cukiernia.png",
        weight: "1.2kg",
        packaging: "Karton 1 szt.",
        ean: "5907552404095",
        temp: "-18°C",
        shelfLife: "6 miesięcy",
        cert: "IFS Food",
        bake: "Rozmrażać przez 4 godziny w temp. 2-6°C",
        desc: "Słodki i wykwintny tort o smaku solonego karmelu. Biszkopty przełożone delikatnym kremem karmelowym i oblane gładką polewą ze słonego toffi, posypane orzechami.",
        ingredients: "Krem karmelowy, toffi solone, orzechy arachidowe (posypka), biszkopt pszenny, śmietanka."
    },
    "tort-truskawkowy": {
        title: "Tort truskawkowy",
        category: "cakes",
        categoryLabel: "Cukiernia",
        image: "img/kategoria_cukiernia.png",
        weight: "1.2kg",
        packaging: "Karton 1 szt.",
        ean: "5907552404101",
        temp: "-18°C",
        shelfLife: "6 miesięcy",
        cert: "IFS Food, BRC",
        bake: "Rozmrażać przez 4 godziny w lodówce",
        desc: "Lekki, letni tort z puszystym musem truskawkowym na bazie naturalnego przecieru z dojrzałych truskawek i śmietany, ozdobiony liofilizowanymi truskawkami.",
        ingredients: "Mus truskawkowy (truskawki 40%, śmietana), jasny biszkopt pszenny, galaretka, truskawki liofilizowane."
    },
    "tort-elizabeth": {
        title: "Tort Elizabeth",
        category: "cakes",
        categoryLabel: "Cukiernia",
        image: "img/kategoria_cukiernia.png",
        weight: "1.3kg",
        packaging: "Karton 1 szt.",
        ean: "5907552404118",
        temp: "-18°C",
        shelfLife: "6 miesięcy",
        cert: "IFS Food, BRC Grade A",
        bake: "Rozmrażać przez 4 godziny w lodówce",
        desc: "Królewski, wielowarstwowy tort premium łączący w sobie smaki chrupiącej bezy, kremu orzechowego oraz kwaskowatej czarnej porzeczki. Wyjątkowy wygląd i kunszt.",
        ingredients: "Krem orzechowy (orzechy włoskie), blaty bezowe, konfitura z porzeczki, krem maślany, dekoracje czekoladowe."
    },

    // --------------------------------------------------------------------------
    // KATEGORIA 4: Produkty półcukiernicze (Drożdżówki, Pączki, Donuty)
    // --------------------------------------------------------------------------
    "drozdzowka-mak": {
        title: "Drożdżówka z makiem",
        category: "sweet",
        categoryLabel: "Półcukiernicze",
        image: "img/drozdzowka.png",
        weight: "90g",
        packaging: "Skrzynka 20 szt. (świeże) / Karton 45 szt. (mrożone)",
        ean: "5907552403050",
        temp: "Dostawa świeża lub mrożona -18°C",
        shelfLife: "48h (Świeża) / 6 miesięcy (Mrożona)",
        cert: "IFS Food",
        bake: "Rozmrażanie: 30 minut, gotowe do spożycia (lub dopiek 3 min w 180°C)",
        desc: "Klasyczna drożdżówka z puszystego, maślanego ciasta drożdżowego z obfitym nadzieniem ze słodkiego maku z bakaliami, posypana chrupiącą kruszonką.",
        ingredients: "Mąka pszenna, nadzienie makowe 30% (mak, cukier, rodzynki), woda, masło, cukier, masa jajowa, kruszonka."
    },
    "drozdzowka-z-serem": {
        title: "Drożdżówka z serem i kruszonką",
        category: "sweet",
        categoryLabel: "Półcukiernicze",
        image: "img/drozdzowka_ser.png",
        weight: "100g",
        packaging: "Skrzynka 20 szt. (świeże) / Karton 40 szt. (mrożone)",
        ean: "5907552403036",
        temp: "Temperatura pokojowa (świeże) lub -18°C",
        shelfLife: "48h (Dostawa świeża) / 6 miesięcy (Mrożona)",
        cert: "IFS Food",
        bake: "Rozmrażanie: 30-40 min w temperaturze pokojowej",
        desc: "Królowa polskich słodkich wypieków – puszysta, maślana drożdżówka z obfitym nadzieniem z naturalnego, słodkiego twarogu, posypana chrupiącą kruszonką.",
        ingredients: "Mąka pszenna typ 500, twaróg słodki naturalny, woda, cukier, masło 82%, drożdże, masa jajowa, kruszonka."
    },
    "gniazdko": {
        title: "Gniazdko z cukrem pudrem / lukrem",
        category: "sweet",
        categoryLabel: "Półcukiernicze",
        image: "img/paczek_malinowy.png",
        weight: "80g",
        packaging: "Karton 40 szt. / Skrzynka 20 szt.",
        ean: "5907552403067",
        temp: "Dostawa świeża lub mrożona",
        shelfLife: "48h / 6 miesięcy",
        cert: "IFS Food",
        bake: "Rozmrażać przez 45 minut w temp. pokojowej",
        desc: "Tradycyjne gniazdko hiszpańskie (pączek z dziurką) wypiekane z lekkiego ciasta parzonego, oblane grubą warstwą lukru cytrynowego lub posypane cukrem pudrem.",
        ingredients: "Jaja kurze, mąka pszenna, woda, cukier (lukier), olej, naturalny aromat cytrynowy."
    },
    "paczek-klasyczny": {
        title: "Pączek delikatesowy / z budyniem / z marmoladą",
        category: "sweet",
        categoryLabel: "Półcukiernicze",
        image: "img/paczek_malinowy.png",
        weight: "80g",
        packaging: "Karton 48 szt. / Skrzynka 24 szt.",
        ean: "5907552403074",
        temp: "Dostawa świeża lub mrożona",
        shelfLife: "48h / 6 miesięcy",
        cert: "IFS Food, BRC",
        bake: "Rozmrażać przez 45 minut w temp. pokojowej",
        desc: "Klasyczny, polski pączek smażony na złocisty kolor, wypełniony tradycyjną marmoladą wieloowocową lub słodkim budyniem waniliowym, dekorowany lukrem chrupiącym.",
        ingredients: "Mąka pszenna typ 500, woda, nadzienie (marmolada / budyń), cukier, tlenek roślinny, drożdże, sól."
    },
    "paczek-premium": {
        title: "Pączek premium z nadzieniem wiśniowym",
        category: "sweet",
        categoryLabel: "Półcukiernicze",
        image: "img/paczek_malinowy.png",
        weight: "100g",
        packaging: "Karton 36 szt. / Paleta: 40 kartonów",
        ean: "5907552403081",
        temp: "-18°C",
        shelfLife: "6 miesięcy",
        cert: "IFS Food, BRC Grade A",
        bake: "Thaw & Serve (rozmrażanie 50-60 min)",
        desc: "Wytworny pączek o podwyższonej gramaturze 100g. Wypełniony po brzegi lekko kwaskowatą, gęstą konfiturą z całych wiśni, ozdobiony pomadą i kandyzowaną skórką pomarańczy.",
        ingredients: "Mąka pszenna, konfitura wiśniowa 22%, woda, jaja, cukier, masło, skórka pomarańczowa kandyzowana."
    },
    "paczek-nadziewany": {
        title: "Pączek z nadzieniem karpatkowym / pistacjowym / malinowym",
        category: "sweet",
        categoryLabel: "Półcukiernicze",
        image: "img/paczek_pistacjowy.png",
        weight: "100g",
        packaging: "Karton 36 szt. / Paleta: 40 kartonów",
        ean: "5907552403043",
        temp: "-18°C",
        shelfLife: "6 miesięcy",
        cert: "IFS Food, BRC",
        bake: "Rozmrażać przez 45-60 minut w temperaturze pokojowej",
        desc: "Luksusowa gama pączków premium wypełnionych aksamitnym kremem karpatkowym, wykwintnym kremem pistacjowym lub naturalną konfiturą malinową, bogato zdobiona.",
        ingredients: "Mąka pszenna, nadzienie (krem pistacjowy / karpatkowy / malina), woda, cukier, jaja, drożdże, posypka."
    },
    "paczek-twarogowy": {
        title: "Pączek twarogowy (mini pączusie serowe)",
        category: "sweet",
        categoryLabel: "Półcukiernicze",
        image: "img/paczek_malinowy.png",
        weight: "25g (Mini pączki w kubku B2B)",
        packaging: "Karton 10 kubków (po 12 szt.)",
        ean: "5907552403098",
        temp: "-18°C",
        shelfLife: "6 miesięcy",
        cert: "IFS Food",
        bake: "Thaw & Serve (rozmrażanie 30 min)",
        desc: "Malutkie, niezwykle puszyste pączuszki serowe, przygotowywane z dodatkiem 30% naturalnego twarogu w ciastku, smażone na złoto i obsypane cukrem pudrem.",
        ingredients: "Twaróg naturalny 30%, mąka pszenna, woda, jaja, cukier, cukier puder, drożdże, sól."
    },
    "paczek-dubajski": {
        title: "Pączek Dubajska Fantazja",
        category: "sweet",
        categoryLabel: "Półcukiernicze",
        image: "img/paczek_pistacjowy.png",
        weight: "100g",
        packaging: "Karton 36 szt. / Paleta: 40 kartonów",
        ean: "5907552403104",
        temp: "-18°C (głęboko mrożone)",
        shelfLife: "6 miesięcy",
        cert: "IFS Food, BRC Grade A",
        bake: "Rozmrażać przez 60 minut w temp. pokojowej",
        desc: "Absolutnie wyjątkowy, zjawiskowy pączek premium inspirowany czekoladą dubajską. Wypełniony kremem pistacjowym z dodatkiem chrupiącego ciasta kataifi, oblany białą czekoladą i pistacjami.",
        ingredients: "Mąka pszenna, krem pistacjowy z kataifi 25%, polewa z białej czekolady, siekane orzechy pistacjowe."
    },
    "donut": {
        title: "Donut z polewą truskawkową / czekoladową",
        category: "sweet",
        categoryLabel: "Półcukiernicze",
        image: "img/paczek_malinowy.png",
        weight: "60g",
        packaging: "Karton 48 szt. / Paleta: 36 kartonów",
        ean: "5907552403111",
        temp: "-18°C",
        shelfLife: "12 miesięcy (Bake-off / Thaw & Serve)",
        cert: "IFS Food, BRC",
        bake: "Rozmrażać przez 30 minut w temp. pokojowej",
        desc: "Amerykański donut (pączek z dziurką) wypiekany z lekkiego, puszystego ciasta drożdżowego, pokryty gładką polewą czekoladową lub truskawkową, posypany kolorową posypką.",
        ingredients: "Mąka pszenna typ 500, woda, polewa (czekoladowa / truskawkowa), cukier, posypka cukrowa, drożdże."
    },
    "rozek-jablko": {
        title: "Rożek z jabłkiem",
        category: "sweet",
        categoryLabel: "Półcukiernicze",
        image: "img/drozdzowka.png",
        weight: "110g",
        packaging: "Karton 50 szt. / Skrzynka 20 szt.",
        ean: "5907552403128",
        temp: "-18°C lub dostawa świeża",
        shelfLife: "48h / 9 miesięcy",
        cert: "IFS Food",
        bake: "Temperatura: 195°C | Czas: 16 minut",
        desc: "Kruchy, trójkątny rożek z ciasta francuskiego, wypełniony gęstą prażoną polską szarą renetą z dodatkiem cynamonu, posypany grubym cukrem perlistym.",
        ingredients: "Ciasto francuskie, jabłka prażone 30% (szara reneta, cynamon, cukier), cukier perlisty."
    },
    "calusek": {
        title: "Całusek",
        category: "sweet",
        categoryLabel: "Półcukiernicze",
        image: "img/drozdzowka.png",
        weight: "90g",
        packaging: "Skrzynka 20 szt.",
        ean: "5907552403135",
        temp: "Dostawa świeża",
        shelfLife: "48h",
        cert: "IFS Food",
        bake: "Produkt gotowy do spożycia",
        desc: "Małe, niezwykle kruche i maślane ciasteczko z ciasta półfrancuskiego, zwinięte z delikatnym nadzieniem owocowym o obniżonej zawartości cukru.",
        ingredients: "Mąka pszenna, masło, marmolada wieloowocowa, śmietanka, woda, sól."
    },
    "racuch": {
        title: "Racuch z jabłkiem",
        category: "sweet",
        categoryLabel: "Półcukiernicze",
        image: "img/drozdzowka.png",
        weight: "80g",
        packaging: "Karton 40 szt. / Skrzynka 20 szt.",
        ean: "5907552403142",
        temp: "Dostawa świeża lub mrożona",
        shelfLife: "48h / 6 miesięcy",
        cert: "IFS Food",
        bake: "Rozmrażać 30 min w temp. pokojowej",
        desc: "Klasyczny, puszysty racuch drożdżowy z dużymi kawałkami świeżych jabłek w środku, usmażony na złoto i oprószony cukrem pudrem. Domowy smak.",
        ingredients: "Mąka pszenna, woda, świeże jabłka 25%, cukier, drożdże, jaja, sól spożywcza."
    },
    "warkocz": {
        title: "Warkocz z lukrem",
        category: "sweet",
        categoryLabel: "Półcukiernicze",
        image: "img/drozdzowka.png",
        weight: "120g",
        packaging: "Skrzynka 15 szt. / Karton 36 szt.",
        ean: "5907552403159",
        temp: "Dostawa świeża lub mrożona",
        shelfLife: "48h / 9 miesięcy",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 195°C | Czas: 15 minut",
        desc: "Puszysty warkocz z ciasta drożdżowo-maślanego, pleciony ręcznie, obficie polany lukrem cukierniczym i posypany skórką pomarańczową. Duży wolumen B2B.",
        ingredients: "Mąka pszenna, masło 82%, woda, cukier, lukier, skórka pomarańczowa, drożdże, sól."
    },
    "rogal-bialy-mak": {
        title: "Rogal świąteczny z białym makiem",
        category: "sweet",
        categoryLabel: "Półcukiernicze",
        image: "img/drozdzowka.png",
        weight: "150g (Premium)",
        packaging: "Karton 24 szt. / Paleta: 40 kartonów",
        ean: "5907552403166",
        temp: "-18°C",
        shelfLife: "6 miesięcy (Łańcuch mrożony)",
        cert: "IFS Food, BRC Grade A",
        bake: "Thaw & Serve (rozmrażanie 60 min)",
        desc: "Prestiżowy rogal premium z ciasta półfrancuskiego, wypełniony po brzegi ekskluzywnym nadzieniem z białego maku, bakalii, migdałów i rodzynek, posypany orzeszkami.",
        ingredients: "Ciasto półfrancuskie, nadzienie z białego maku 35% (biały mak, marcepan, rodzenki, migdały), orzechy (posypka), lukier."
    },

    // --------------------------------------------------------------------------
    // KATEGORIA 5: Kanapki i Słone przekąski
    // --------------------------------------------------------------------------
    "kanapka-kurczak": {
        title: "Kanapka firmowa z wędzonym kurczakiem",
        category: "bistro",
        categoryLabel: "Kanapki i Przekąski",
        image: "img/kategoria_kanapki.png",
        weight: "180g (Pakowanie Flow-pack MAP)",
        packaging: "Karton zbiorczy 12 szt. (dostawa świeża chłodnicza)",
        ean: "5907552406013",
        temp: "Kontrolowana temperatura chłodnicza (2-6°C)",
        shelfLife: "48h (Codzienna logistyka świeżości)",
        cert: "IFS Food, BRC",
        bake: "Produkt gotowy do spożycia na zimno lub do podgrzania (panini)",
        desc: "Świeża kanapka bistro przygotowywana na bazie chrupiącego pieczywa rzemieślniczego własnej produkcji Leks. Wypełniona plastrami soczystego wędzonego kurczaka, sałatą i sosem.",
        ingredients: "Bułka rzemieślnicza pszenna, wędzona pierś z kurczaka 25%, pomidor, ogórek, sałata zielona, sos majonezowo-ziołowy."
    },
    "kanapka-gyros": {
        title: "Kanapka Sulejmana z mięsem gyros",
        category: "bistro",
        categoryLabel: "Kanapki i Przekąski",
        image: "img/kategoria_kanapki.png",
        weight: "200g ( MAP Flow-pack)",
        packaging: "Karton zbiorczy 12 szt. (dostawa świeża)",
        ean: "5907552406020",
        temp: "Kontrolowana temperatura chłodnicza (2-6°C)",
        shelfLife: "48h (Logistyka chłodnicza)",
        cert: "IFS Food, BRC",
        bake: "Produkt gotowy do bezpośredniego spożycia (lub podgrzania w opiekaczu)",
        desc: "Pożywna, flagowa kanapka bistro (200g) na bazie chrupiącego pieczywa pszennego. Wypełniona aromatycznym pieczonym mięsem drobiowym Gyros/Kebab i sosem czosnkowym.",
        ingredients: "Pieczywo pszenne, pieczone mięso z kurczaka (gyros) 25%, kapusta pekińska, ogórek konserwowy, sos czosnkowy, przyprawy."
    },
    "kanapka-poledwica": {
        title: "Kanapka szefa z polędwicą",
        category: "bistro",
        categoryLabel: "Kanapki i Przekąski",
        image: "img/kategoria_kanapki.png",
        weight: "180g (MAP Flow-pack)",
        packaging: "Karton zbiorczy 12 szt.",
        ean: "5907552406037",
        temp: "Chłodnicza (2-6°C)",
        shelfLife: "48h",
        cert: "IFS Food, BRC",
        bake: "Produkt gotowy do spożycia",
        desc: "Świeża, lekka kanapka na chrupiącej bagietce wieloziarnistej z plastrami wykwintnej polędwicy sopockiej, świeżą rzodkiewką, szczypiorkiem i kremowym serek masłowym.",
        ingredients: "Bagietka wieloziarnista, polędwica sopocka 25%, rzodkiewka, szczypiorek, twarogowy serek kremowy, masło."
    },
    "bulka-warzywa": {
        title: "Bułka z warzywami",
        category: "bistro",
        categoryLabel: "Kanapki i Przekąski",
        image: "img/kategoria_przekaski.png",
        weight: "120g",
        packaging: "Karton 50 szt. / Paleta: 32 kartony",
        ean: "5907552405030",
        temp: "-18°C",
        shelfLife: "9 miesięcy (Bake-off)",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 195°C | Czas: 14-16 minut",
        desc: "Pożywna bułka śniadaniowa z wytrawnym, gęstym farszem z warzyw korzeniowych, cebuli i groszku, zapieczona ze złocistym serem. Doskonałe B2B Bake-off.",
        ingredients: "Mąka pszenna, woda, farsz warzywny 20% (marchew, groszek, cebula, kukurydza), mozzarella, drożdże, sól."
    },
    "przekaska-warzywa": {
        title: "Przekąska z warzywami",
        category: "bistro",
        categoryLabel: "Kanapki i Przekąski",
        image: "img/kategoria_przekaski.png",
        weight: "150g",
        packaging: "Karton 40 szt. / Paleta: 32 kartony (1280 szt.)",
        ean: "5907552405023",
        temp: "-18°C (Łańcuch głębokiego mrożenia)",
        shelfLife: "9 miesięcy (Bake-off)",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 195°C | Czas: 16-18 minut bez rozmrażania",
        desc: "Wytrawna przekąska B2B o podwyższonej gramaturze (150g). Chrupiące ciasto francuskie wypełnione bogatym, śródziemnomorskim farszem warzywnym i mozzarella.",
        ingredients: "Mąka pszenna, farsz warzywny (papryka, cukinia, pomidory, cebula, kukurydza), woda, mozzarella, drożdże, sól."
    },
    "paluch-ser": {
        title: "Paluch z serem",
        category: "bistro",
        categoryLabel: "Kanapki i Przekąski",
        image: "img/kategoria_przekaski.png",
        weight: "80g",
        packaging: "Karton 60 szt. / Paleta: 32 kartony",
        ean: "5907552405047",
        temp: "-18°C",
        shelfLife: "9 miesięcy (Bake-off)",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 200°C | Czas: 10-12 minut bez rozmrażania",
        desc: "Tradycyjny, podłużny paluch z ciasta pszennego rzemieślniczego, obficie posypany na wierzchu i zapieczony z pikantnym, aromatycznym żółtym serem Gouda.",
        ingredients: "Mąka pszenna typ 500, woda, ser Gouda tarty 20%, drożdże, tłuszcz roślinny, sól spożywcza."
    },
    "slimak-szpinak": {
        title: "Ślimak ze szpinakiem",
        category: "bistro",
        categoryLabel: "Kanapki i Przekąski",
        image: "img/kategoria_przekaski.png",
        weight: "100g",
        packaging: "Karton 60 szt. / Paleta: 32 kartony (1920 szt.)",
        ean: "5907552405016",
        temp: "-18°C (Łańcuch głębokiego mrożenia)",
        shelfLife: "9 miesięcy (Bake-off)",
        cert: "IFS Food, BRC",
        bake: "Temperatura: 190-200°C | Czas: 15-18 minut z parowaniem",
        desc: "Chrupiąca przekąska z wielowarstwowego, puszystego ciasta francuskiego, zwinięta w kształt ślimaka i obficie wypełniona wytrawnym farszem ze szpinaku i fety.",
        ingredients: "Mąka pszenna, woda, szpinak liściasty 18%, margaryna piekarnicza, ser feta, cebula, czosnek, sól, pieprz."
    },
    "bite-4-smaki": {
        title: "Bite (4 smaki)",
        category: "bistro",
        categoryLabel: "Kanapki i Przekąski",
        image: "img/kategoria_przekaski.png",
        weight: "140g",
        packaging: "Karton 40 szt. / Paleta: 32 kartony",
        ean: "5907552405054",
        temp: "-18°C",
        shelfLife: "9 miesięcy (Bake-off)",
        cert: "IFS Food, BRC Grade A",
        bake: "Temperatura: 195°C | Czas: 15 minut",
        desc: "Innowacyjna słona przekąska bankietowa podzielona na 4 połączone segmenty (bite), z których każdy zawiera inne nadzienie (pieczarka, szpinak, ser-szynka, pomidor-mozzarella).",
        ingredients: "Mąka pszenna, margaryna, nadzienia wytrawne 25% (pieczarkowe, szpinakowe, szynka z serem, pomidor z mozzarella), woda, sól."
    }
};

// Eksportujemy bazę danych dla przeglądarki i modułów node
if (typeof module !== 'undefined' && module.exports) {
    module.exports = PRODUCTS_DATA;
}
